version: 2

workflows:
  version: 2
  default:
    jobs:
      - xcode-10
      - xcode-9

step-library:
  - &restore-cache
      restore_cache:
        keys:
          - carthage-cache-mbdirections-v1-{{ .Environment.CIRCLE_JOB }}-{{ checksum "Cartfile.resolved" }}
          - carthage-cache-mbdirections-v1- # used if checksum fails

  - &save-cache
      save_cache:
        key: carthage-cache-mbdirections-v1-{{ .Environment.CIRCLE_JOB }}-{{ checksum "Cartfile.resolved" }}
        paths:
          - Carthage

  - &prepare
      run:
        name: Prepare
        command: |
          git submodule sync
          if (brew outdated | grep carthage > /dev/null); then brew upgrade carthage; fi
          echo "foo" > ~/.mapbox

  - &install-dependencies
      run:
        name: Install Dependencies
        command: |
          carthage bootstrap --platform ios --cache-builds --no-use-binaries
          carthage bootstrap --platform tvos --cache-builds --no-use-binaries
          carthage bootstrap --platform macos --cache-builds --no-use-binaries
          carthage bootstrap --platform watchos --cache-builds --no-use-binaries

  - &build-test-MapboxDirections-ios-11
      run:
        name: Build and Test MapboxDirections for iOS 11
        command: |
          xcodebuild -sdk iphonesimulator -project MapboxDirections.xcodeproj -scheme 'MapboxDirections iOS' -destination 'platform=iOS Simulator,OS=11.4,name=iPhone 6 Plus' clean build test

  - &build-test-MapboxDirections-ios-12
      run:
        name: Build and Test MapboxDirections for iOS 12
        command: |
          xcodebuild -sdk iphonesimulator -project MapboxDirections.xcodeproj -scheme 'MapboxDirections iOS' -destination 'platform=iOS Simulator,OS=12.0,name=iPhone 6 Plus' clean build test

  - &build-MapboxDirections-watchos-4
    run:
      name: Build MapboxDirections for watchOS 4
      command: |
        xcodebuild -project MapboxDirections.xcodeproj -scheme 'MapboxDirections watchOS' -destination 'platform=watchOS Simulator,name=Apple Watch Series 3 - 42mm,OS=4.2' clean build

  - &build-MapboxDirections-watchos-5
    run:
      name: Build MapboxDirections for watchOS 5
      command: |
        xcodebuild -project MapboxDirections.xcodeproj -scheme 'MapboxDirections watchOS' -destination 'platform=watchOS Simulator,name=Apple Watch Series 3 - 42mm,OS=5.0' clean build

  - &build-test-MapboxDirections-tvos-12
    run:
      name: Build and Test MapboxDirections for tvOS 12
      command: |
        xcodebuild -project MapboxDirections.xcodeproj -scheme 'MapboxDirections tvOS' -destination 'platform=tvOS Simulator,name=Apple TV 4K (at 1080p),OS=12.0' clean build test

  - &build-test-MapboxDirections-macos
    run:
      name: Build and Test MapboxDirections for macOS
      command: |
        xcodebuild -project MapboxDirections.xcodeproj -scheme 'MapboxDirections Mac' clean build test | xcpretty

jobs:
  xcode-10:
    macos:
      xcode: "10.0.0"
    environment:
      HOMEBREW_NO_AUTO_UPDATE: 1
    steps:
      - checkout
      - *prepare
      - *restore-cache
      - *install-dependencies
      - *build-test-MapboxDirections-ios-12
      - *build-MapboxDirections-watchos-5
      - *build-test-MapboxDirections-tvos-12
      - *build-test-MapboxDirections-macos
      - *save-cache

  xcode-9:
    macos:
      xcode: "9.4.1"
    environment:
      HOMEBREW_NO_AUTO_UPDATE: 1
    steps:
      - checkout
      - *prepare
      - *restore-cache
      - *install-dependencies
      - *build-test-MapboxDirections-ios-11
      - *build-MapboxDirections-watchos-4
      - *build-test-MapboxDirections-macos
      - *save-cache
